<form class="form-inline" role="form">
	<div class="form-group">
		<select class="form-control input-sm">
			<option>Pilih Tahun</option>
			<?php foreach ($this->annualPeriodSelection as $annualPeriod) : ?>
			<option></option>
			<?php endforeach;?>
		</select>
	</div>
	<div class="form-group">
		<select class="form-control input-sm">
			<option>Pilih Wilayah</option>
			<?php foreach ($this->territorySelection as $territory) : ?>
			<option></option>
			<?php endforeach;?>
		</select>
	</div>
</form>
<div class="row">
	<div id='chartcolumncontainer<?php echo $this->id ?>'></div>
</div>
<?php
$this->inlineScript()->captureStart();
?>
$(function () {
	$('#chartcolumncontainer<?php echo $this->id ?>').highcharts({
		chart: {
			type: 'column'
		},
		title: {
			text: '<?php echo $this->chartTitle ?>'
		},
		xAxis: {
			categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
		},
		yAxis: {
			allowDecimals: false,
			min: 0,
			title: {
				text: 'Number of fruits'
			}
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.x +'</b><br/>'+
					this.series.name +': '+ this.y +'<br/>'+
					'Total: '+ this.point.stackTotal;
			}
		},
		plotOptions: {
			column: {
				stacking: 'normal'
			}
		},
		series: [
			{
				name: 'John',
				data: [5, 3, 4, 7, 2],
				stack: 'male'
			},
			{
				name: 'Joe',
				data: [3, 4, 4, 2, 5],
				stack: 'male'
			},
			{
				name: 'Jhon',
				data: [2, 5, 6, 2, 1],
				stack: 'female'
			},
			{
				name: 'Janet',
				data: [3, 0, 4, 4, 3],
				stack: 'female'
			}
		]
	});
});
<?php
$this->inlineScript()->captureEnd();
?>