<div class="panel panel-default">
	<div class="panel-body">
		<h2>Update Database Schema</h2>
		<div class="alert alert-info alert-dismissable">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <strong>Success!</strong> Update database schema completed. <a href="<?php echo $this->url('schema', array('action' => 'index'))?>" class="alert-link">Kembali</a>
		</div>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>No</th>
					<th>SQL</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->createSql as $index => $sql) : ?>
				<tr>
					<td style="text-align: center;"><?php echo $index+1 ?></td>
					<td><?php echo $sql ?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>