<div class="panel panel-default">
	<div class="panel-body">
		<h2>Manage Database Schema</h2>
		<p>Halaman ini khusus untuk development.</p>
		<a href="<?php echo $this->url('schema', array('action' => 'create'))?>" class="btn btn-default">Update Schema</a>
		<a href="<?php echo $this->url('schema', array('action' => 'validate'))?>" class="btn btn-default">Validate Schema</a>
		<a href="<?php echo $this->url('schema', array('action' => 'drop'))?>" class="btn btn-warning">Drop Schema</a>
	</div>
</div>