<div class="panel panel-default">
	<div class="panel-body">
		<h2>Validate Database Schema</h2>
		<?php if($this->errors) :?>
		<div class="alert alert-danger alert-dismissable">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <strong>Error!</strong> Validate database schema completed with errors <a href="<?php echo $this->url('schema', array('action' => 'index'))?>" class="alert-link">Kembali</a>
		</div>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Entity</th>
					<th>SQL</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->errors as $index => $error) : ?>
				<tr>
					<td style="text-align: center;"><?php echo $index ?></td>
					<td>
						<ul>
						<?php foreach ($error as $e) : ?>
							<li><?php echo $e?></li>
						<?php endforeach;?>
						</ul>
					</td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<?php else : ?>
		<div class="alert alert-info alert-dismissable">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <strong>Success!</strong> Validate database schema completed without error <a href="<?php echo $this->url('schema', array('action' => 'index'))?>">Kembali</a>
		</div>
		<?php endif;?>
	</div>
</div>