<?php 
$this->headTitle('Expenditure');
?>
	<div class="page-header">
		<h1>Data Expenditure</h1>
	</div>
	<div>
		<div class="row">
			<div class="col-md-8">
				<ul class="nav nav-pills">
					<li><a href="#">Tambah</a></li>
					<li><a href="#">Update</a></li>
					<li><a href="#">Hapus</a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<div class="input-group-btn">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Filter Kolom <span class="caret"></span></button>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>
					</div>
					<input type="text" class="form-control">
					<span class="input-group-btn">
						<button class="btn btn-default" type="button">Search</button>
					</span>
				</div>
			</div>
		</div>
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th style="width: 25px;">No</th>
					<th style="width: 150px;">Tahun Anggaran</th>
					<th>Daerah</th>
					<th style="width: 250px;">Fungsi Pengeluaran</th>
					<th style="width: 250px;">Jenis Belanja</th>
					<th style="width: 150px;">Jumlah</th>
					<th style="width: 75px;">Aksi</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td style="text-align: center;">1</td>
					<td>2001</td>
					<td>Kota Lhokseumawe</td>
					<td>Pariwisata Dan Kebudayaan</td>
					<td>Belanja Infrastruktur</td>
					<td>Rp 1.232.323.232</td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
				<tr>
					<td style="text-align: center;">2</td>
					<td>2002</td>
					<td>Kota Lhokseumawe</td>
					<td>Pariwisata Dan Kebudayaan</td>
					<td>Belanja Infrastruktur</td>
					<td>Rp 1.232.323.232</td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
				<tr>
					<td style="text-align: center;">3</td>
					<td>2003</td>
					<td>Kota Lhokseumawe</td>
					<td>Pariwisata Dan Kebudayaan</td>
					<td>Belanja Infrastruktur</td>
					<td>Rp 1.232.323.232</td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<ul class="pagination">
			<li class="disabled"><a href="#">&laquo;</a></li>
			<li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
			<li><a href="#">2 <span class="sr-only">(current)</span></a></li>
			<li><a href="#">3 <span class="sr-only">(current)</span></a></li>
			<li><a href="#">4 <span class="sr-only">(current)</span></a></li>
			<li><a href="#">5 <span class="sr-only">(current)</span></a></li>
			<li><a href="#">&raquo;</a></li>
		</ul>
	</div>