<?php 
use Zend\Mvc\Controller\Plugin\FlashMessenger;
$loginForm = $this->loginForm;
$loginForm->prepare();
?>

<div class="page-header">
	<h1>Login</h1>
</div>
<div class="row">
	<div class="col-md-8">
		<p>Silahkan gunakan form di samping ini untuk masuk ke dalam sistem. Jika Anda belum terdaftar, silahkan register <a>di sini</a>.
	</div>
	<div class="col-md-4">
		<?php if($this->errorMessage) : ?>
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<?php echo $this->errorMessage ?>
		</div>
		<?php endif; ?>
		<?php 
			echo $this->form()->openTag($loginForm);
		?>
			<div class="form-group">
				<label for="inputEmail3" class="col-sm-4 control-label">Username</label>
				<div class="col-sm-8">
					<?php echo $this->formInput($loginForm->get('username')) ?>
				</div>
			</div>
			<div class="form-group">
				<label for="inputPassword3" class="col-sm-4 control-label">Password</label>
				<div class="col-sm-8">
					<?php echo $this->formPassword($loginForm->get('password'))?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-8">
					<div class="checkbox">
						<label>
							<?php echo $this->formCheckbox($loginForm->get('rememberme'))?> Remember me
						</label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-8">
					<?php 
					echo $this->formElement($loginForm->get('submit'));
					?>
				</div>
			</div>
		<?php 
			echo $this->formElement($loginForm->get('security'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>