<?php 
$this->headTitle('Income');
?>
	<div class="page-header">
		<h1>Data Income</h1>
	</div>
	<div>
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th style="width: 25px;">No</th>
					<th style="width: 150px;">Tahun Anggaran</th>
					<th>Daerah</th>
					<th style="width: 250px;">Sumber Penerimaan</th>
					<th style="width: 150px;">Jumlah</th>
					<th style="width: 75px;">Aksi</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td style="text-align: center;">1</td>
					<td>2001</td>
					<td>Kota Lhokseumawe</td>
					<td>Dana Alokasi Khusus</td>
					<td>Rp 1.232.323.232</td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
				<tr>
					<td style="text-align: center;">2</td>
					<td>2002</td>
					<td>Kota Lhokseumawe</td>
					<td>Dana Alokasi Khusus</td>
					<td>Rp 1.232.323.232</td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>