<?php 
$this->headTitle('Template');
?>
	<div class="page-header">
		<h1>Template Laporan</h1>
	</div>
	<div>
		<table class="table">
			<thead>
				<tr>
					<th style="width: 25px;">No</th>
					<th style="width: 200px;">Template</th>
					<th>Keterangan</th>
					<th style="width: 200px;">Pemilik</th>
					<th style="width: 75px;">Publik</th>
					<th style="width: 75px;">Aksi</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td style="text-align: center;">1</td>
					<td>Template Pertama</td>
					<td>Keterangan Template Pertama</td>
					<td>Muhammad Zaky Alvan</td>
					<td></td>
					<td>
						<div class="dropdown">
							<a class="dropdown-toggle" style="text-align: center;" data-toggle="dropdown" href="#">Aksi</a>
							<ul class="dropdown-menu">
								<li><a href="#">Lihat</a></li>
								<li class="divider"></li>
								<li><a href="#">Hapus</a></li>
							</ul>
 						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>